name: Publish Node.js Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        buildTarget:
          - name: gaudi-iot-device
            path: device/core/
          - name: gaudi-iot-amqp-base
            path: common/transport/amqp/
          - name: gaudi-iot-device-amqp
            path: device/transport/amqp/

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Grant execute permission to edit_packageJSON.sh
      run: chmod +x ./scripts/edit_packageJSON.sh

    - name: Run edit_packageJSON.sh ({{ matrix.buildTarget.name }})
      run: |
        export PATH="/usr/bin:/bin:$PATH"
        ./scripts/edit_packageJSON.sh
      env: 
        NAME: ${{ matrix.buildTarget.name }}
        PATH: "${{ matrix.buildTarget.path }}package.json"
        VERSION: ${{ github.event.release.tag_name }}

    - name: Set Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com/'
    
    - name: Install Dependencies
      run: |
        npm install --global node-gyp
      
    - name: Bootstrap & Build ({{ matrix.buildTarget.name }})
      run: lerna run build --scope {{ matrix.buildTarget.name }}

    - name: Publish to GitHub Packages ({{ matrix.buildTarget.name }})
      run: npm publish {{ matrix.buildTarget.path }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
